### ISSUE TITLE
Using Gilded Plate crashes the game

### ISSUE THREAD

**Issue by GitUser14975** [bpoletti/Ancient_Artifacts_Mod#26]
When I tried right clicking with the Gilded Plate in hand, the game crashed. Ancient Artifacts was the only mod I was playing with. Here's the crash log:
https://gist.github.com/TenKotowsky/7c86f0530d84d62f0d96f04af944895f

**Comment by bpoletti** [comment]
Issue should be fixed with [Version 1.0.21](https://legacy.curseforge.com/minecraft/mc-mods/ancient-artifacts-fabric/files/4599994)/ [Version 1.0.21](https://modrinth.com/mod/ancient_artifacts/changelog) 
Apparently there was an issue with all of the blocks with Horizontal vs Vertical directions for 1.20 exclusively.
